name: Tests

on:
  push:
  pull_request:
    branches: [master]

# Current configuration:
# - python 3.9, django 3.2, wagtail 4.1
# - python 3.9, django 4.1, wagtail 4.2
# - python 3.9, django 4.2, wagtail 5.0

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
      - run: pip install -e .[lint]
      - name: Run flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run isort
        run: isort . --check-only --diff
      - name: Run black
        run: black . --check --fast
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: "3.9"
            django: django>=3.2,<4.0
            wagtail: wagtail>=4.1,<4.2
          - python: "3.9"
            django: django>=4.2,<4.3
            wagtail: wagtail>=5.1,<5.2
          - python: "3.9"
            django: django>=4.2,<4.3
            wagtail: wagtail>=5.2,<5.3

          - python: "3.10"
            django: django>=3.2,<4.0
            wagtail: wagtail>=4.1,<4.2
          - python: "3.10"
            django: django>=4.2,<4.3
            wagtail: wagtail>=5.1,<5.2
          - python: "3.10"
            django: django>=4.2,<4.3
            wagtail: wagtail>=5.2,<5.3

          - python: "3.11"
            django: django>=4.2,<4.3
            wagtail: wagtail>=5.1,<5.2
          - python: "3.11"
            django: django>=4.2,<4.3
            wagtail: wagtail>=5.2,<5.3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
      - run: |
          pip install coverage
          pip install "${{ matrix.wagtail }}"
      - run: |
          coverage run ./runtests.py
          coverage report
          coverage xml
      - if: ${{ matrix.latest }}
        uses: codecov/codecov-action@v2
        with:
          name: Python 3.9
